name: "macos-all"

env:
  os: MacOS

on: push

jobs:
  test:
    runs-on: "macos-latest"
    steps:
      - name: Delete Release
        shell: bash --noprofile --norc {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          release_name="${{ env.os }}"
          release_id=$(curl -s -X GET -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/releases" | jq ".[] | select(.name == \"$release_name\") | .id")
          if [ ! -z "$release_id" ]; then
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/releases/$release_id"
          else
            echo "Release not found."
          fi
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Test
        shell: bash --noprofile --norc {0}
        run: |-
          wget -q -O mermaid-electron.dmg 'https://github.com/whinee/mermaid-electron/releases/download/latest/mermaid-electron.dmg'
          just --evaluate
          just bootstrap
          $(just --evaluate pyenv_activate_cmd)
          python all.py
      - name: Upload PNGs
        uses: AButler/upload-release-assets@v2.0
        with:
          bodyFile: 'results.md'
          files: '*.png'
          allowUpdates: true
          removeArtifacts: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.os }}