on:
  workflow_dispatch
jobs:
  test:
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: test
        run: "python -m pip install -r all_req.txt; python -m pip install -r ${{ matrix.os }}_req.txt; python all.py"