on:
  workflow_dispatch
jobs:
  win:
    runs-on: windows-latest
    steps:
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: test
        run: python -c "import os;print(os.getenv('username'))"
