on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Test
        run: |-
          echo "$RUNNER_OS"
          python -m pip install -r all_req.txt
          python -m pip install -r "$RUNNER_OS"_req.txt
          ( python all.py 3>&1 1>&2- 2>&3- ) | python -c "$(cat rmm.py)"'
          main("Windows")'
        shell: /bin/bash --noprofile --norc
      - name: Commit to repository
        run: |-
          git add .
          git commit -m "Update README.md"
          git fetch origin master
          git push origin HEAD:master