env:
  os: ubuntu
name: "${{ env.os }}-all"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["macos-all"]
    types:
      - completed
jobs:
  test:
    runs-on: "${{ env.os }}-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Test
        run: |-
          echo "${{ env.os }}"
          python -m pip install -r all_req.txt
          python -m pip install -r "${{ env.os }}"_req.txt
          ( python all.py 3>&1 1>&2- 2>&3- ) | python -c "$(cat rmm.py)"'
          main("${{ env.os }}")'
        shell: /bin/bash --noprofile --norc {0}
      - name: Commit to repository
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update README.md"
          git fetch origin master
          git push origin HEAD:master