name: "ubuntu-all"
run-name: "ubuntu-all"

env:
  os: ubuntu

on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - shell: bash --noprofile --norc {0}
        name: Test
        run: |-
          echo "${{ env.os }}" > os
          python -m pip install -r all_req.txt
          python -m pip install -r "${{ env.os }}"_req.txt
          ( python all.py 3>&1 1>&2- 2>&3- ) | python rmm.py
          cat README.md
      - name: Commit to repository
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . --dry-run
          git add README.md
          git commit -m "Update README.md"
          git push