name: "ubuntu-all"

env:
  os: Linux

on: push

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Test
        shell: bash --noprofile --norc {0}
        run: |-
          just bootstrap
          source "$(just --evaluate pyenv_activate)"
          wget -O mermaid-electron.AppImage 'https://github.com/whinee/mermaid-electron/releases/download/latest/mermaid-electron.AppImage'
          python all.py
      - name: Delete Release
        shell: bash --noprofile --norc {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_name="${{ env.os }}"
          release_id=$(curl -s -X GET -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases" | jq ".[] | select(.name == \"$release_name\") | .id")
          if [ ! -z "$release_id" ]; then
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
          else
            echo "Release not found."
          fi
      - name: Read Release Message From File
        id: read_release_message
        shell: bash --noprofile --norc {0}
        run: |
          release_message=$(cat results.md)
          echo "::set-output name=message::$release_message"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.os }}
          release_name: ${{ env.os }}
          body: ${{ steps.read_release_message.outputs.message }}
          draft: false
          prerelease: false