run-name: ${{ github.event.client_payload.os }}-all

env:
  os: ${{ github.event.client_payload.os }}

on:
  repository_dispatch:
    types: [macos-all]

jobs:
  test:
    runs-on: ${{ github.event.client_payload.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - shell: bash --noprofile --norc {0}
        name: Test
        run: |-
          echo ${{ github.event.client_payload.os }} > os
          python -m pip install -r all/req/all.txt
          python -m pip install -r all/req/${{ github.event.client_payload.os }}.txt
          python all.py
      - name: Commit to repository
        if: always()
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . --dry-run
          git add README.md
          git commit -m "Update README.md"
          git push